<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Run On Chrome"
           tests="3"
           failures="1"
           errors="0"
           skipped="0"
           time="7.797">
    <properties></properties>

            <testcase
                name="User_03_My_Account"
                time="0.894"
                classname="user.Level_18_Patten_Object">

            <failure type="java.lang.AssertionError" message="expected [FC] but found [Automation]">
                <![CDATA[java.lang.AssertionError: expected [FC] but found [Automation]
                org.testng.Assert.fail(Assert.java:97)org.testng.Assert.assertEqualsImpl(Assert.java:136)org.testng.Assert.assertEquals(Assert.java:118)org.testng.Assert.assertEquals(Assert.java:575)org.testng.Assert.assertEquals(Assert.java:585)user.Level_18_Patten_Object.User_03_My_Account(Level_18_Patten_Object.java:115)java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)java.base/java.lang.reflect.Method.invoke(Method.java:568)org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)java.base/java.util.ArrayList.forEach(ArrayList.java:1511)org.testng.TestRunner.privateRun(TestRunner.java:766)org.testng.TestRunner.run(TestRunner.java:587)org.testng.SuiteRunner.runTest(SuiteRunner.java:384)org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)org.testng.SuiteRunner.run(SuiteRunner.java:286)org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)org.testng.TestNG.runSuitesLocally(TestNG.java:1109)org.testng.TestNG.runSuites(TestNG.java:1039)org.testng.TestNG.run(TestNG.java:1007)com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
            </failure>
    </testcase>


            <testcase
                name="Login_02_Login"
                time="3.399"
                classname="user.Level_18_Patten_Object">
            </testcase>
            <testcase
                name="Login_01_Register_Login_My_Account"
                time="3.504"
                classname="user.Level_18_Patten_Object">
            </testcase>
</testsuite>
